# Generated by Django 4.0.4 on 2022-05-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=32)),
                ('family_name', models.CharField(blank=True, max_length=32)),
                ('alignmnet', models.CharField(choices=[('LG', 'Lawful Good'), ('LN', 'Lawful Neutral'), ('LE', 'Lawful Evil'), ('NG', 'Neutral Good'), ('TN', 'True Neutral'), ('NE', 'Neutral Evil'), ('CG', 'Chaotic Good'), ('CN', 'Chaotic Neutral'), ('CE', 'Chaotic Evil')], max_length=32)),
                ('pronoun', models.CharField(choices=[('they', 'They/Them'), ('she', 'She/Her'), ('he', 'he/him')], max_length=32)),
                ('npc_class', models.CharField(choices=[('Commoner', 'Commoner'), ('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard'), ('Artificer', 'Artificer'), ('Blood Hunter', 'Blood Hunter')], default='Commoner', max_length=32)),
                ('npc_race', models.CharField(choices=[('Dragonborn', 'Dragonborn'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Gnome', 'Gnome'), ('Half-Elf', 'Half-Elf'), ('Halfling', 'Halfling'), ('Half-Orc', 'Half-Orc'), ('Human', 'Human'), ('Teifling', 'Teifling'), ('Aarakocra', 'Aarakocra'), ('Genasi', 'Genasi'), ('Goliath', 'Goliath'), ('Aasimar', 'Aasimar'), ('Bugbear', 'Bugbear'), ('Firbolg', 'Firbolg'), ('Goblin', 'Goblin'), ('Hobgoblin', 'Hobgoblin'), ('Kenku', 'Kenku'), ('Kobold', 'Kobold'), ('Lizardfolk', 'Lizardfolk'), ('Orc', 'Orc'), ('Tabaxi', 'Tabaxi'), ('Triton', 'Triton'), ('Yuan-ti Pureblood', 'Yuan-ti Pureblood'), ('Tortle', 'Tortle'), ('Gith', 'Gith')], max_length=32)),
                ('age', models.IntegerField(default=20)),
                ('physical', models.CharField(blank=True, max_length=1024)),
                ('profession', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.campaign')),
            ],
            options={
                'ordering': ['family_name'],
            },
        ),
    ]
