# Generated by Django 4.0.4 on 2022-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='pronoun',
            field=models.CharField(choices=[('they', 'They/Them'), ('she', 'She/Her'), ('he', 'He/Him')], max_length=32),
        ),
    ]
