# Generated by Django 4.0.4 on 2022-05-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_campaign_created_at_campaign_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
