# Generated by Django 4.0.4 on 2022-05-12 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_npc_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='alignmnet',
            new_name='alignment',
        ),
    ]
